name: Core Library CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:

jobs:
  test-core:
    name: Core - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - name: Checkout on core
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf \
            autoconf-archive \
            automake \
            libtool \
            pkg-config

      - name: Install macOS dependencies
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install autoconf autoconf-archive automake libtool pkg-config

      # No additionnal dependencies required for Windows

      - name: Install vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: "${{ github.workspace }}/vcpkg"

      - name: Configurer CMake
        run: >
          cmake
          -S .
          -B build
          -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Compile core
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
